USE olmabank;
GO

INSERT INTO olmabank_hr.Departments (ManagerID, DepartmentName) VALUES
(1, 'Finance'),
(2, 'IT'),
(3, 'HR'),
(4, 'Marketing'),
(5, 'Operations'),
(6, 'Sales'),
(7, 'Compliance'),
(8, 'Customer Support'),
(9, 'Logistics'),
(10, 'Risk Management'),
(11, 'Product Development'),
(12, 'Corporate Strategy'),
(13, 'Business Intelligence'),
(14, 'Investment Banking'),
(15, 'Private Banking'),
(16, 'Credit Analysis'),
(17, 'Treasury'),
(18, 'Internal Audit'),
(19, 'Public Relations'),
(20, 'Vendor Management'),
(21, 'Payroll'),
(22, 'Retail Banking'),
(23, 'Corporate Lending'),
(24, 'Trade Finance'),
(25, 'Capital Markets'),
(26, 'Wealth Management'),
(27, 'Data Science'),
(28, 'Cyber Security'),
(29, 'Legal Affairs'),
(30, 'Loan Processing'),
(31, 'Fraud Prevention'),
(32, 'Consumer Lending'),
(33, 'Customer Insights'),
(34, 'Open Banking'),
(35, 'Branch Management'),
(36, 'Technology Risk'),
(37, 'Financial Planning'),
(38, 'ATM Operations'),
(39, 'Trust Services'),
(40, 'Syndicated Loans'),
(41, 'ESG & Sustainability'),
(42, 'KYC Compliance'),
(43, 'Regulatory Affairs'),
(44, 'Performance Management'),
(45, 'Product Innovation'),
(46, 'Employee Relations'),
(47, 'AI & Automation'),
(48, 'Credit Risk'),
(49, 'Anti-Money Laundering'),
(50, 'Foreign Exchange Trading');
GO
