USE olmabank;
GO
INSERT INTO olmabank_hr.Departments (DepartmentName, ManagerID) VALUES
('Finance', 63),
('Human Resources', 5),
('IT', 87),
('Marketing', 68),
('Sales', 31),
('Operations', 83),
('Legal', 56),
('Customer Support', 45),
('Risk Management', 3),
('Compliance', 93),
('Procurement', 94),
('Logistics', 36),
('Strategy', 79),
('Product Development', 34),
('R&D', 89),
('Internal Audit', 19),
('Corporate Communications', 26),
('Security', 19),
('Facilities Management', 33),
('Investor Relations', 2),
('Treasury', 58),
('Digital Banking', 24),
('Retail Banking', 50),
('Corporate Banking', 93),
('SME Banking', 3),
('Insurance', 77),
('Wealth Management', 72),
('Asset Management', 71),
('Mortgage Services', 37),
('Payments & Settlements', 73),
('Call Center', 8),
('Fraud Prevention', 99),
('Business Intelligence', 23),
('Regulatory Affairs', 31),
('AML Compliance', 86),
('Credit Risk', 50),
('Market Risk', 31),
('Operational Risk', 85),
('Cybersecurity', 51),
('Governance', 17),
('Tax Advisory', 34),
('Data Science', 93),
('AI & Automation', 49),
('Public Relations', 98),
('Business Development', 27),
('Legal Affairs', 53),
('Training & Development', 66),
('Employee Relations', 73),
('Compensation & Benefits', 15),
('Payroll', 71),
('Investment Banking', 47),
('Private Banking', 4),
('Foreign Exchange', 29),
('Trade Finance', 17),
('Retail Operations', 58),
('Corporate Lending', 41),
('Consumer Lending', 67),
('Capital Markets', 77),
('Syndicated Loans', 64),
('Financial Planning', 48),
('Performance Management', 40),
('Corporate Strategy', 18),
('ESG & Sustainability', 89),
('Credit Analysis', 76),
('Loan Servicing', 51),
('Vendor Management', 47),
('Financial Reporting', 32),
('Internal Controls', 68),
('Technology Risk', 92),
('Software Development', 23),
('Infrastructure Management', 89),
('Network Security', 6),
('Help Desk', 59),
('Application Support', 61),
('Cloud Services', 6),
('Data Governance', 77),
('Data Engineering', 20),
('Mobile Banking', 5),
('Wealth Advisory', 52),
('Trust Services', 75),
('Branch Management', 100),
('Customer Insights', 31),
('Banking Innovation', 97),
('Open Banking', 22),
('Client Relationship Management', 14),
('Digital Transformation', 12),
('ATM Management', 52),
('Cash Management', 18),
('Anti-Bribery & Corruption', 46),
('Retail Strategy', 25),
('Loan Processing', 6),
('KYC Operations', 65),
('Fraud Analytics', 58),
('IT Security', 13),
('Business Process Management', 97),
('Customer Experience', 48),
('Employee Wellbeing', 11),
('Risk Analytics', 23),
('Retail Lending', 53),
('Corporate Social Responsibility', 18);
GO
